import re
from typing import List


class TextFilter:
    """Provides sanitization, regex matching, and artifact removal for OCR text."""

    @staticmethod
    def remove_isolated_symbols(text: str) -> str:
        # Removes noise characters often generated by OCR errors
        return re.sub(r'(?<=\s)[^\w\s](?=\s)', '', text)

    @staticmethod
    def normalize_whitespace(text: str) -> str:
        # Replaces consecutive spaces or mixed tabs with single spaces
        text = re.sub(r'[ \t]+', ' ', text)
        return re.sub(r'\n\s*\n', '\n', text).strip()

    @staticmethod
    def extract_patterns(text: str, pattern: str) -> List[str]:
        return re.findall(pattern, text)

    def clean(self, text: str) -> str:
        cleaned = self.remove_isolated_symbols(text)
        cleaned = self.normalize_whitespace(cleaned)
        return cleaned